### ISSUE TITLE
Add End of the game function

### ISSUE THREAD

**Issue by stevelikeafox** [stevelikeafox/axe-throwing#1]
# check the top score display winner and score. If draw enters sudden death (kill shot).

### Extra functions.
Sudden Death
In the event of a tie after 10 throws in a single match, the match enters into sudden death.
The Killshot is activated during all sudden death throws
Players will switch lanes and throw. This will happen for every Sudden Death Throw
The player in the left target will always throw first
Final Throws
If after 5 consecutive sudden death throws a winner has not been determined, all subsequent throws must be for the killshot only until a winner is determined
Only the killshot is activated during the 6th and subsequent sudden death throws
This means that no rings or the bullseye on the target are active

**Comment by steve-will-dev** [comment]
all game mechanics now complete. MVP Done.
